---
title: "NCBirths Analysis"
author: "Matt Robinson, Athena Higgins, Ethan Sennett, Peter Nguyen"
date: "11/23/2016"
output: html_document
---

```{r setup, echo=FALSE}
library(ggplot2)
library(Stat2Data)
data(NCbirths)
```

# Table of Contents

1. Project Overview
2. Individual Data Analyses
    + Race vs Age
    + Weight Gained vs Age
    + Child Weight vs Weeks of Gestation
    + Child Weight vs Multiple Births
3. Conclusion

\newpage

## Project Overview

For our final project, based on the NCbirths dataset, we will explore factors related to childbirth data at a particular hospital. The NCbirths dataset includes the following variables that will be useful in exploring the stories contained in this dataset.

**Variable**   |  **Explanation**
-------------- | -----------------
MomAge         | The mothers age.
Marital        | The marital status of the mother. 1 = married, 2 = not married.
MomRace        | Mother's race: black, hispanic, other, or white.
Gained         | The amount of weight gained during pregnancy (in pounds).
BirthWeightOz	 | The birth weight of the child (in ounces).
Weeks          | The number of completed weeks of gestation.
Plural         | Multiple birth indicator. 1=single birth, 2=twins, 3=triplets.


details about the mother (age, smoking status, race, weight gained during pregnancy etc.) and information about the infant (weight, weeks gestation, etc.). Examining relationships among these factors provides insight into the complexity of pregnancy for women and their infants, and the plethora of variables which influence childbirth. Some interesting relationships and interactions that we will explore in this report include:

1. The relationship between the mothers marital status, race and age.
2. The relationship between the mothers marital status, weight gained during pregnancy and age.
3. The relationship between the mothers marital status, the childs weight at birth and number of weeks of gestation.
4. The relationship between the mothers marital status, the childs weight at birth and whether or not the child was a twin or triplet.

Analyzing the data, through lenses shaped by these factors, allows us to tell intriguing social and biological stories about women’s pregnancy experiences. All of these analyses will incorporate marital status as a categorical factor to provide a comprehensive analysis of marital influence on pregnancy and childbirth.

We will use our analysis to prove or disprove the following hypotheses regarding marital status and pregnancy:

1. Hypothesis 1

2. Hypothesis / Exploration 2- Interpreting data related to marital status, race, and age will allow for an intriguing discussion of social factors related to childbirth, and insight into the influence of these factors on pregnancy. Marital status and race are not biological factors, and thus should have no physical influence on childbirth. When different patterns emerge in the childbirth data, with respect to these variables, trends could indicate the influence of social pressures and climate on childbirth. 

## Code for Missing Data, example

NCbirths$MomAge_mis <- factor(is.na(NCbirths$MomAge))
#
mosaic::tally(~MomAge|MomAge_mis, data=NCbirths)
#
NCbirths1 <- dplyr::filter(NCbirths, MomAge_mis==FALSE)

\newpage

## Race and Age



\newpage

## Weight Gained and Age



\newpage

## Child Weight and Weeks of Gestation



\newpage

## Child Weight and Multiple Births



\newpage

